CREATE TABLE TipoEquipos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Marcas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Estados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TipoComponentes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Componentes(
  id INT AUTO_INCREMENT PRIMARY KEY,
  idTipoComponente INT,
  idMarca INT,
  codigoInventario VARCHAR(50) UNIQUE,
  fechaDeAdquisicion DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (idTipoComponente) REFERENCES TipoComponentes(id),
  FOREIGN KEY (idMarca) REFERENCES Marcas(id)
);

CREATE TABLE TipoMantenimientos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Fallas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  descripcion VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Equipos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idTipoEquipo INT,
  idMarca INT,
  idEstado INT,
  fechaDeAdquisicion DATE,
  ultimoMantenimiento DATE,
  proximoMantenimiento DATE,
  codigoInventario VARCHAR(50) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (idTipoEquipo) REFERENCES TipoEquipos(id),
  FOREIGN KEY (idMarca) REFERENCES Marcas(id),
  FOREIGN KEY (idEstado) REFERENCES Estados(id)
);

CREATE TABLE Mantenimientos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idEquipo INT,
  idTipoDeMantenimiento INT,
  descripcion VARCHAR(255),
  solucionesImplementadas VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ticket VARCHAR(20) GENERATED ALWAYS AS (
    CONCAT(
      DATE_FORMAT(created_at, '%Y%m%d'),
      '-',
      LPAD(idEquipo, 3, '0')
    )
  ) VIRTUAL,
  FOREIGN KEY (idEquipo) REFERENCES Equipos(id),
  FOREIGN KEY (idTipoDeMantenimiento) REFERENCES TipoMantenimientos(id)
);

CREATE TABLE Equipo_Componente(
  id INT AUTO_INCREMENT PRIMARY KEY,
  idEquipo INT,
  idComponente INT,
  observaciones VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (idEquipo) REFERENCES Equipos(id),
  FOREIGN KEY (idComponente) REFERENCES Componentes(id)
);

CREATE TABLE Mantenimiento_Falla(
  id INT AUTO_INCREMENT PRIMARY KEY,
  idMantenimiento INT,
  idFalla INT,
  observaciones VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (idMantenimiento) REFERENCES Mantenimientos(id),
  FOREIGN KEY (idFalla) REFERENCES Fallas(id)
);

  