/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resources.views;

import resources.components.FlexWrapLayout;
import resources.components.ScrollBarCustom;
import app.Interfaces.SelectedAction;
import resources.components.datechooser.SelectedDate;
import app.Controllers.ComponentController;
import app.Controllers.EquipmentController;
import app.Models.EquipmentType;
import app.Models.Brand;
import app.Models.State;
import app.Requests.StoreComponentRequest;
import app.Requests.StoreEquipmentRequest;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author carlosvargas
 */
public class CreateEquipmentPanel extends javax.swing.JPanel {

    protected String _BASEDIR = System.getProperty("user.dir");
    protected String _IMAGE_PATH = _BASEDIR + "/src/main/java/resources/images/";

    /**
     * Creates new form NewRegisterPanel
     */
    public CreateEquipmentPanel() {
        initComponents();

        dateChooser.addEventDateChooser((SelectedAction action, SelectedDate date) -> {
            if (action.getAction() == SelectedAction.DAY_SELECTED) {
                dateChooser.hidePopup();
            }
        });

        dateChooser1.addEventDateChooser((SelectedAction action, SelectedDate date) -> {
            if (action.getAction() == SelectedAction.DAY_SELECTED) {
                dateChooser1.hidePopup();
            }
        });

        ScrollBarCustom verticalScrollBar = new ScrollBarCustom();
        verticalScrollBar.setForeground(new Color(130, 130, 130, 100));
        ScrollPanelComponents.setVerticalScrollBar(verticalScrollBar);

        EquipmentType.all("nombre", jComboBoxTypeEq);
        Brand.all("nombre", jComboBoxBrands);
        State.all("nombre", jComboBoxStates);

        ButtonHoverEffect(AddComponentBtn, _IMAGE_PATH + "AddComponentBtn.png", _IMAGE_PATH + "AddComponentActiveBtn.png");
        ButtonHoverEffect(CancelBtn, _IMAGE_PATH + "CancelBtn.png", _IMAGE_PATH + "CancelActiveBtn.png");

        ContainerPanel.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$App.default.background;");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new resources.components.datechooser.DateChooser();
        dateChooser1 = new resources.components.datechooser.DateChooser();
        ContainerPanel = new javax.swing.JPanel();
        jlabelTitle = new javax.swing.JLabel();
        EquipmentPanel = new resources.components.PanelShadow();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxBrands = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTypeEq = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateAcquisitionEq = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxStates = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDateAdBtn = new javax.swing.JButton();
        jDateLastMaintenance = new javax.swing.JFormattedTextField();
        jLabelErrorAcquisitionDate = new javax.swing.JLabel();
        jlabelErrorTypeEq = new javax.swing.JLabel();
        JlabelErrorInventoryCode = new javax.swing.JLabel();
        jLabelErrorState = new javax.swing.JLabel();
        jLabelErrorBrand = new javax.swing.JLabel();
        jLabelErrorlastMaintenance = new javax.swing.JLabel();
        jTextFieldInvCode = new javax.swing.JTextField();
        ComponentsPanel = new resources.components.PanelShadow();
        ScrollPanelComponents = new javax.swing.JScrollPane();
        MiddlePanelComponent = new javax.swing.JPanel();
        AddComponentBtn = new javax.swing.JLabel();
        CancelBtn = new javax.swing.JLabel();
        jLabelBtnCreate = new javax.swing.JLabel();
        jlabelTitle1 = new javax.swing.JLabel();

        dateChooser.setForeground(new java.awt.Color(36, 104, 155));
        dateChooser.setTextRefernce(jDateLastMaintenance);

        dateChooser1.setForeground(new java.awt.Color(36, 104, 155));
        dateChooser1.setTextRefernce(jDateAcquisitionEq);

        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1271, 738));
        setPreferredSize(new java.awt.Dimension(1271, 738));

        ContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContainerPanel.setMinimumSize(new java.awt.Dimension(1251, 732));
        ContainerPanel.setPreferredSize(new java.awt.Dimension(1251, 732));

        jlabelTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlabelTitle.setText("CREAR EQUIPO");

        EquipmentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Codigo de Inventario");

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/PlusBtn.png")); // NOI18N
        jLabel8.setToolTipText("Agregar nueva Marca");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("Marca");

        jLabel6.setText("Ultimo Mantenimiento");

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/PlusBtn.png")); // NOI18N
        jLabel7.setToolTipText("Agregar nuevo tipo de equipo");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText("Tipo de Equipo");

        jDateAcquisitionEq.setBackground(new java.awt.Color(255, 255, 255));
        jDateAcquisitionEq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));

        jLabel5.setText("Fecha de Aquisicion");

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/PlusBtn.png")); // NOI18N
        jLabel9.setToolTipText("Agregar nuevo estado");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("Estado");

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jDateAdBtn.setText("...");
        jDateAdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateAdBtnActionPerformed(evt);
            }
        });

        jDateLastMaintenance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));

        jLabelErrorAcquisitionDate.setForeground(java.awt.Color.red);
        jLabelErrorAcquisitionDate.setMaximumSize(new java.awt.Dimension(2000, 0));
        jLabelErrorAcquisitionDate.setMinimumSize(new java.awt.Dimension(0, 18));
        jLabelErrorAcquisitionDate.setPreferredSize(new java.awt.Dimension(0, 18));

        jlabelErrorTypeEq.setForeground(java.awt.Color.red);
        jlabelErrorTypeEq.setMaximumSize(new java.awt.Dimension(2000, 0));
        jlabelErrorTypeEq.setMinimumSize(new java.awt.Dimension(0, 18));
        jlabelErrorTypeEq.setPreferredSize(new java.awt.Dimension(0, 18));

        JlabelErrorInventoryCode.setForeground(java.awt.Color.red);
        JlabelErrorInventoryCode.setMaximumSize(new java.awt.Dimension(2000, 0));
        JlabelErrorInventoryCode.setMinimumSize(new java.awt.Dimension(0, 18));
        JlabelErrorInventoryCode.setPreferredSize(new java.awt.Dimension(0, 18));

        jLabelErrorState.setForeground(java.awt.Color.red);
        jLabelErrorState.setInheritsPopupMenu(false);
        jLabelErrorState.setMaximumSize(new java.awt.Dimension(2000, 0));
        jLabelErrorState.setMinimumSize(new java.awt.Dimension(0, 18));
        jLabelErrorState.setPreferredSize(new java.awt.Dimension(0, 18));

        jLabelErrorBrand.setForeground(java.awt.Color.red);
        jLabelErrorBrand.setMaximumSize(new java.awt.Dimension(2000, 0));
        jLabelErrorBrand.setMinimumSize(new java.awt.Dimension(0, 18));
        jLabelErrorBrand.setPreferredSize(new java.awt.Dimension(0, 18));

        jLabelErrorlastMaintenance.setForeground(java.awt.Color.red);
        jLabelErrorlastMaintenance.setMaximumSize(new java.awt.Dimension(2000, 0));
        jLabelErrorlastMaintenance.setMinimumSize(new java.awt.Dimension(0, 18));
        jLabelErrorlastMaintenance.setPreferredSize(new java.awt.Dimension(0, 18));

        javax.swing.GroupLayout EquipmentPanelLayout = new javax.swing.GroupLayout(EquipmentPanel);
        EquipmentPanel.setLayout(EquipmentPanelLayout);
        EquipmentPanelLayout.setHorizontalGroup(
            EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EquipmentPanelLayout.createSequentialGroup()
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelErrorlastMaintenance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlabelErrorInventoryCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(189, 189, 189))
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addComponent(jDateLastMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldInvCode, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                        .addGap(64, 64, 64)))
                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addComponent(jComboBoxBrands, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32))
                            .addComponent(jlabelErrorTypeEq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                        .addComponent(jComboBoxTypeEq, 0, 358, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)))
                        .addGap(32, 32, 32))
                    .addComponent(jLabelErrorBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addComponent(jComboBoxStates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(78, 78, 78))
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addComponent(jLabelErrorAcquisitionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addComponent(jDateAcquisitionEq, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateAdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(84, 84, 84))))
        );
        EquipmentPanelLayout.setVerticalGroup(
            EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jDateAcquisitionEq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateAdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldInvCode)))
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelErrorAcquisitionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabelErrorTypeEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JlabelErrorInventoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                    .addComponent(jComboBoxStates))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelErrorState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxBrands, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateLastMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelErrorBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelErrorlastMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 38, Short.MAX_VALUE))
                    .addGroup(EquipmentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(EquipmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTypeEq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        ComponentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ComponentsPanel.setMaximumSize(new java.awt.Dimension(32767, 3000));
        ComponentsPanel.setPreferredSize(new java.awt.Dimension(1233, 292));

        ScrollPanelComponents.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanelComponents.setBorder(null);
        ScrollPanelComponents.setForeground(new java.awt.Color(255, 255, 255));
        ScrollPanelComponents.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanelComponents.setMaximumSize(new java.awt.Dimension(32767, 2000));
        ScrollPanelComponents.setPreferredSize(new java.awt.Dimension(0, 204));

        MiddlePanelComponent.setBackground(new java.awt.Color(255, 255, 255));
        MiddlePanelComponent.setLayout(new javax.swing.BoxLayout(MiddlePanelComponent, javax.swing.BoxLayout.LINE_AXIS));
        ScrollPanelComponents.setViewportView(MiddlePanelComponent);

        AddComponentBtn.setBackground(java.awt.Color.white);
        AddComponentBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddComponentBtn.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/AddComponentBtn.png")); // NOI18N
        AddComponentBtn.setNextFocusableComponent(AddComponentBtn);
        AddComponentBtn.setOpaque(true);
        AddComponentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddComponentBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ComponentsPanelLayout = new javax.swing.GroupLayout(ComponentsPanel);
        ComponentsPanel.setLayout(ComponentsPanelLayout);
        ComponentsPanelLayout.setHorizontalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ScrollPanelComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddComponentBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ComponentsPanelLayout.setVerticalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentsPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ScrollPanelComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddComponentBtn)
                .addGap(30, 30, 30))
        );

        CancelBtn.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/CancelBtn.png")); // NOI18N
        CancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelBtnMouseClicked(evt);
            }
        });

        jLabelBtnCreate.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/CreateBtn.png")); // NOI18N
        jLabelBtnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBtnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBtnCreateMouseClicked(evt);
            }
        });

        jlabelTitle1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlabelTitle1.setText("AGREGAR COMPONENTES");

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelBtn)
                .addGap(45, 45, 45)
                .addComponent(jLabelBtnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlabelTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanelLayout.createSequentialGroup()
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ComponentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EquipmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlabelTitle)))))
                .addGap(26, 26, 26))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EquipmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComponentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBtnCreate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showPanel(JPanel panel) {
        this.removeAll();
        this.revalidate();
        this.repaint();
        this.setLayout(new BorderLayout());
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    private void CancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBtnMouseClicked
        showPanel(new EquipmentPanel());
    }//GEN-LAST:event_CancelBtnMouseClicked

    private void jLabelBtnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBtnCreateMouseClicked
        ArrayList<Integer> componentIds = new ArrayList<>();

        StoreComponentRequest ComponentRequest = new StoreComponentRequest();

        ComponentRequest.setParameter("panel", MiddlePanelComponent);
        ComponentRequest.setParameter("array", componentIds);

        ComponentController.store(ComponentRequest);

        StoreEquipmentRequest EquipmentRequest = new StoreEquipmentRequest();

        EquipmentRequest.setParameter("type", jComboBoxTypeEq.getSelectedItem().toString());
        EquipmentRequest.setParameter("brand", jComboBoxBrands.getSelectedItem().toString());
        EquipmentRequest.setParameter("state", jComboBoxStates.getSelectedItem().toString());
        EquipmentRequest.setParameter("acquisitionDate", jDateAcquisitionEq.getText());
        EquipmentRequest.setParameter("lastMaintenance", jDateLastMaintenance.getText());
        EquipmentRequest.setParameter("inventoryCode", jTextFieldInvCode.getText());
        EquipmentRequest.setParameter("componentIds", componentIds);

        if (EquipmentRequest.validate()) {
            EquipmentController.store(EquipmentRequest);
            showPanel(new EquipmentPanel());
        } else {
            setErrorMessage(jlabelErrorTypeEq, EquipmentRequest.getErrors().get("type"));
            setErrorMessage(jLabelErrorBrand, EquipmentRequest.getErrors().get("brand"));
            setErrorMessage(jLabelErrorState, EquipmentRequest.getErrors().get("state"));
            setErrorMessage(jLabelErrorAcquisitionDate, EquipmentRequest.getErrors().get("acquisitionDate"));
            setErrorMessage(jLabelErrorlastMaintenance, EquipmentRequest.getErrors().get("lastMaintenance"));
            setErrorMessage(JlabelErrorInventoryCode, EquipmentRequest.getErrors().get("inventoryCode"));
        }
    }//GEN-LAST:event_jLabelBtnCreateMouseClicked

    public void setErrorMessage(JLabel label, String message) {
        label.setText(message);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jDateAdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateAdBtnActionPerformed
        dateChooser1.showPopup();
    }//GEN-LAST:event_jDateAdBtnActionPerformed

    private void AddComponentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddComponentBtnMouseClicked
        MiddlePanelComponent.setLayout(new FlexWrapLayout(FlowLayout.LEFT, 40, 20));

        CreateComponentPanel component = (CreateComponentPanel) ComponentController.create();

        component.setComponentListener((CreateComponentPanel panel) -> {
            MiddlePanelComponent.remove(panel);
            MiddlePanelComponent.revalidate();
            MiddlePanelComponent.repaint();
        });

        MiddlePanelComponent.add(component);
        MiddlePanelComponent.revalidate();
        MiddlePanelComponent.repaint();

    }//GEN-LAST:event_AddComponentBtnMouseClicked

    private void ButtonHoverEffect(JLabel button, String defaultIconPath, String activeIconPath) {
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setIcon(new ImageIcon(activeIconPath));
                button.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setIcon(new ImageIcon(defaultIconPath));
                button.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddComponentBtn;
    private javax.swing.JLabel CancelBtn;
    private resources.components.PanelShadow ComponentsPanel;
    private javax.swing.JPanel ContainerPanel;
    private resources.components.PanelShadow EquipmentPanel;
    private javax.swing.JLabel JlabelErrorInventoryCode;
    private javax.swing.JPanel MiddlePanelComponent;
    private javax.swing.JScrollPane ScrollPanelComponents;
    private resources.components.datechooser.DateChooser dateChooser;
    private resources.components.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxBrands;
    private javax.swing.JComboBox<String> jComboBoxStates;
    private javax.swing.JComboBox<String> jComboBoxTypeEq;
    private javax.swing.JFormattedTextField jDateAcquisitionEq;
    private javax.swing.JButton jDateAdBtn;
    private javax.swing.JFormattedTextField jDateLastMaintenance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBtnCreate;
    private javax.swing.JLabel jLabelErrorAcquisitionDate;
    private javax.swing.JLabel jLabelErrorBrand;
    private javax.swing.JLabel jLabelErrorState;
    private javax.swing.JLabel jLabelErrorlastMaintenance;
    private javax.swing.JTextField jTextFieldInvCode;
    private javax.swing.JLabel jlabelErrorTypeEq;
    private javax.swing.JLabel jlabelTitle;
    private javax.swing.JLabel jlabelTitle1;
    // End of variables declaration//GEN-END:variables
}
