/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resources.views;

import app.Interfaces.SelectedAction;
import resources.components.datechooser.SelectedDate;
import app.Interfaces.ComponentListener;
import app.Models.Brand;
import app.Models.ComponentType;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author carlosvargas
 */
public class CreateComponentPanel extends javax.swing.JPanel {

    protected String _BASEDIR = System.getProperty("user.dir");
    protected String _ICONS_PATH = _BASEDIR + "/src/main/java/resources/icons/";
    private ComponentListener componentListener;

    /**
     * Creates new form CreateComponentPanel
     */
    public CreateComponentPanel() {
        initComponents();

        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$App.default.background;");

        dateChooserComponent.addEventDateChooser((SelectedAction action, SelectedDate date) -> {
            if (action.getAction() == SelectedAction.DAY_SELECTED) {
                dateChooserComponent.hidePopup();
            }
        });

        ComponentType.all("nombre", jComboBoxComponentType);
        Brand.all("nombre", jComboBoxBrands);

        ButtonHoverEffect(DeleteComponentBtn, _ICONS_PATH + "TrashIcon.png", _ICONS_PATH + "SelectedTrashIcon.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserComponent = new resources.components.datechooser.DateChooser();
        jTextFieldInvCodeComponent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxComponentType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxBrands = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateAcquisitionComponent = new javax.swing.JFormattedTextField();
        jDateAcquisitionInComponent = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DeleteComponentBtn = new javax.swing.JLabel();

        dateChooserComponent.setForeground(new java.awt.Color(36, 104, 155));
        dateChooserComponent.setTextRefernce(jDateAcquisitionComponent);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setText("Codigo de Inventario");

        jLabel1.setText("Tipo de componente");

        jLabel7.setToolTipText("Agregar nuevo tipo de equipo");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/images/PlusBtn.png")); // NOI18N
        jLabel8.setToolTipText("Agregar nueva Marca");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("Marca");

        jDateAcquisitionComponent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));

        jDateAcquisitionInComponent.setText("...");
        jDateAcquisitionInComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateAcquisitionInComponentActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de Aquisicion");

        DeleteComponentBtn.setIcon(new javax.swing.ImageIcon("/home/carlosvargas/NetBeansProjects/OPTIMUS PRIME/OPTIMUS/src/main/java/resources/icons/TrashIcon.png")); // NOI18N
        DeleteComponentBtn.setToolTipText("Eliminar");
        DeleteComponentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteComponentBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateAcquisitionComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateAcquisitionInComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldInvCodeComponent))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxComponentType, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))))
                    .addComponent(DeleteComponentBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DeleteComponentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxComponentType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldInvCodeComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateAcquisitionComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateAcquisitionInComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxBrands)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jDateAcquisitionInComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateAcquisitionInComponentActionPerformed
        dateChooserComponent.showPopup();
    }//GEN-LAST:event_jDateAcquisitionInComponentActionPerformed

    private void DeleteComponentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteComponentBtnMouseClicked
        if (componentListener != null) {
            componentListener.onComponentDeleteRequested(this);
        }
    }//GEN-LAST:event_DeleteComponentBtnMouseClicked

    public void setComponentListener(ComponentListener listener) {
        this.componentListener = listener;
    }

    private void ButtonHoverEffect(JLabel button, String defaultIconPath, String activeIconPath) {
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setIcon(new ImageIcon(activeIconPath));
                button.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setIcon(new ImageIcon(defaultIconPath));
                button.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeleteComponentBtn;
    private resources.components.datechooser.DateChooser dateChooserComponent;
    public javax.swing.JComboBox<String> jComboBoxBrands;
    public javax.swing.JComboBox<String> jComboBoxComponentType;
    public javax.swing.JFormattedTextField jDateAcquisitionComponent;
    private javax.swing.JButton jDateAcquisitionInComponent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField jTextFieldInvCodeComponent;
    // End of variables declaration//GEN-END:variables
}
