/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resources.views;

import app.Controllers.MaintenanceController;
import com.formdev.flatlaf.FlatClientProperties;
import com.mindfusion.common.DateTime;
import com.mindfusion.scheduling.Calendar;
import com.mindfusion.scheduling.CalendarView;
import com.mindfusion.scheduling.ThemeType;
import java.awt.BorderLayout;
import java.util.Locale;

/**
 *
 * @author carlosvargas
 */
public class SchedulePanel extends javax.swing.JPanel {

    private Calendar calendar;

    /**
     * Creates new form SchedulePanel
     */
    public SchedulePanel() {
        initComponents();

        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$App.default.background;");

        jSidePanel.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$App.default.background;");

        CalendarPanel.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$App.default.background;");

        jTextFieldSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Buscar");

        initCalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTitle = new javax.swing.JLabel();
        CalendarPanel = new javax.swing.JPanel();
        jSidePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNextMaintenance = new javax.swing.JList<>();
        jTextFieldSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1271, 738));
        setPreferredSize(new java.awt.Dimension(1271, 738));

        jlabelTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlabelTitle.setText("CALENDARIO");

        CalendarPanel.setBackground(java.awt.Color.white);
        CalendarPanel.setMinimumSize(new java.awt.Dimension(1043, 690));
        CalendarPanel.setPreferredSize(new java.awt.Dimension(1043, 684));
        CalendarPanel.setLayout(new java.awt.BorderLayout());

        jSidePanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        jListNextMaintenance.setBorder(javax.swing.BorderFactory.createTitledBorder("Proximos Mantenimientos"));
        jListNextMaintenance.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Equipo LAB08-0042 - Correctivo", "Equipo LAB08-0042 - Preventivo", "Equipo LAB08-0030 - Correctivo", "Equipo LAB08-0032 - Correctivo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListNextMaintenance.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListNextMaintenance.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setViewportView(jListNextMaintenance);

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        jScrollPane2.setBorder(null);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimientos no realizados"));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Equipo LAB08-0032 - No realizado", "Equipo LAB08-0042 - No realizado", "Equipo LAB08-0030 - No realizado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jSidePanelLayout = new javax.swing.GroupLayout(jSidePanel);
        jSidePanel.setLayout(jSidePanelLayout);
        jSidePanelLayout.setHorizontalGroup(
            jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSidePanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jSidePanelLayout.setVerticalGroup(
            jSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlabelTitle))
                    .addComponent(jSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CalendarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 896, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(CalendarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        String searchText = jTextFieldSearch.getText();

        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            fillTable(searchText.isEmpty() ? EquipmentController.index() : EquipmentController.show(searchText));
        }*/
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void initCalendar() {
        calendar = new Calendar(Locale.forLanguageTag("ES"));
        calendar.beginInit();
        calendar.setCurrentView(CalendarView.SingleMonth);
        calendar.setTheme(ThemeType.Light);
        calendar.getMonthSettings().getDaySettings().setShowToday(Boolean.TRUE);
        calendar.setDate(new DateTime(DateTime.today().getYear(), DateTime.today().getMonth(), 1));
        calendar.setEndDate(new DateTime(DateTime.today().getYear(), DateTime.today().getMonth(), 28));
        calendar.endInit();

        MaintenanceController.index(calendar, jListNextMaintenance);

        CalendarPanel.add(calendar, BorderLayout.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalendarPanel;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jListNextMaintenance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jSidePanel;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel jlabelTitle;
    // End of variables declaration//GEN-END:variables
}
